[tool.poetry]
name = "pyquickshare"
version = "0.1.0"
description = ""
authors = ["teaishealthy <teaishealthy@protonmail.com>"]
license = "ISC"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
zeroconf = "^0.132.2"
protobuf = "^5.26.1"
cryptography = "^42.0.7"
bless = "^0.2.6"
dbus-python = "^1.3.2"

[tool.poetry.group.dev.dependencies]
ruff = "^0.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
